<?php

namespace AppBundle\Repository;

/**
 * ComposeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposeRepository extends \Doctrine\ORM\EntityRepository
{
}
