<?php

namespace AppBundle\Repository;

/**
 * EndroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EndroitRepository extends \Doctrine\ORM\EntityRepository
{
}
