<?php

namespace AppBundle\Repository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $id
     * @return \VB\RecetteBundle\Entity\Recette[]
     */
    public function getFullRecette($id)
    {
        $qb = $this
            ->createQueryBuilder('r')
            ->leftJoin('r.categorie', 'cat')
            ->addSelect('cat')
            ->leftJoin('r.famille','fam')
            ->addSelect('fam')
            ->leftJoin('r.pays','pay')
            ->addSelect('pay')
            ->leftJoin('r.image','img')
            ->addSelect('img')
            ->leftJoin('r.etapes','etape')
            ->addSelect('etape')
            ->where('r.id = :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
