<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Categorie;
use AppBundle\Entity\Famille;
use AppBundle\Entity\Recette;
use Doctrine\ORM\EntityRepository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends EntityRepository
{

    /**
     * @param $id
     * @return Recette[]
     */
    public function getFullRecette($id)
    {
        $qb = $this
            ->createQueryBuilder('r')
            ->leftJoin('r.categorie', 'cat')
            ->addSelect('cat')
            ->leftJoin('r.boissons', 'boi')
            ->addSelect('boi')
            ->leftJoin('r.famille','fam')
            ->addSelect('fam')
            ->leftJoin('r.image','img')
            ->addSelect('img')
            ->leftJoin('r.etapes','etape')
            ->addSelect('etape')
            ->where('r.id = :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findLastNumberWithFamilyAndCategory( $famille, $categorie)
    {
        return $this->createQueryBuilder('r')
            ->select('r.numero')
            ->leftJoin('r.categorie', 'cat')
            ->where('cat = :categorie')
            ->setParameter('categorie', $categorie)
            ->leftJoin('r.famille','fam')
            ->andWhere('fam = :famille')
            ->setParameter('famille', $famille)

            ->orderBy('r.numero', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getScalarResult();
    }
}
