<?php

namespace AppBundle\Repository;

/**
 * RecetteEndroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteEndroitRepository extends \Doctrine\ORM\EntityRepository
{
}
