<?php

namespace AppBundle\Repository;

/**
 * TypeQuantiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeQuantiteRepository extends \Doctrine\ORM\EntityRepository
{
}
