<?php

namespace AppBundle\Repository;

/**
 * UniteMesureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniteMesureRepository extends \Doctrine\ORM\EntityRepository
{
}
