services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateur", label: User }

    admin.famille:
        class: AppBundle\Admin\FamilleAdmin
        arguments: [~, AppBundle\Entity\Famille, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Configuration", label: Famille }

    admin.categorie:
        class: AppBundle\Admin\CategorieAdmin
        arguments: [~, AppBundle\Entity\Categorie, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Configuration", label: Categorie }
