services:
    admin.unite_mesure:
        class: AppBundle\Admin\UniteMesureAdmin
        arguments: [~, AppBundle\Entity\UniteMesure, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: UniteMesure }

    app.admin.endroit:
        class: AppBundle\Admin\EndroitAdmin
        arguments: [~, AppBundle\Entity\Endroit, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Endroit }

    app.admin.boisson:
        class: AppBundle\Admin\BoissonAdmin
        arguments: [~, AppBundle\Entity\Boisson, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Boisson }
